title: "SET09102 Software Engineering"
remote_theme: just-the-docs/just-the-docs
exclude:
  - api/
color_scheme: napier
favicon_ico: "/images/Napier.png"
compress_html:
  ignore:
    envs: all
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
  math_engine: katex
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  information:
    title: Information
    color: yellow
  tip:
    title: Tip
    color: green
